### ISSUE TITLE
Endpoint Authentication Configuration

### ISSUE THREAD

**Issue by RemeJuan** [contentjet/contentjet-api#2]
Been playing around for a few hours (you may recall from reddit the guy with the odd docker issue).

Looking at the swagger, I see most of the endpoints require authentication and I cannot see any configuration for this, and while some most certainly should be authenticated, things like `Entry` and `Media` at the very least should be auth configurable. In it's current setup this makes it very unsecured to use on a public facing site if I were to want to use this as a replacement for something like a wordpress blog, I would need to hardcode authentication in order to fetch back content.

I would actually be quite happy to help on the UI implementation side of this, when I get my  new machine next week will see about setting everything up locally, but great work so far. Definitely the best implementation of a headless CMS I have seen so far.

**Comment by willdady** [comment]
Hi @RemeJuan. Currently authentication with the API is achieved via submitting your email/password to the backend in exchange for a short-lived access token. Specifically this is the OAuth2 Resource Owner Password Credentials Grant flow. You can read more about it [here](https://contentjet.github.io/documentation/API/).

In it's current form, the API isn't really suited for unauthenticated read access at least not directly. What I mean is a frontend cannot access the API without first providing authentication, something which wouldn't work in a public facing 'blog' like website as you would need to store credentials on the frontend which would be **very** insecure.

I'm currently working on adding OAuth2 Client Credentials flow which will allow you to register a 'client' with the API. This will provide a way of accessing a Project with read-only access. This will hopefully be done in a few days.

Glad you're liking it.

**Comment by willdady** [comment]
Just an update on this. The latest versions, contentjet-api@0.13.0 and contentjet-ui@0.7.0, now support **OAuth2 Client Credentials** flow. Documentation has been updated [here](https://contentjet.github.io/documentation/API/).

**Comment by RemeJuan** [comment]
Awesome, pulling the updates now.
