### ISSUE TITLE
Fetch all entries ( Including Fields ) by entryTypeId

### ISSUE THREAD

**Issue by ACatThatPrograms** [contentjet/contentjet-api#4]
Really like how streamlined this is for a headless API so I started playing around with it.

I'm not sure if this is possible though... 

I've been trying to fetch all entries by entryTypeId to then look at their respective fields etc. without hitting the API up numerous times on a single entry call for each respective entryId

I tried `/project/1/entry/?entryType=2`

To fetch all of entryTypeId === 2, And it returns entries, but those entry blobs do not have the fields that I associated with them when creating entry types.

Right now I am looking at the possibility of pushing all the matching entry ids from that request to `/project/1/entry/x` Where x is each id I pulled from the previous request, but this would lead to a large amount of API calls on any large scale platform.

Am I missing something?

**Comment by willdady** [comment]
Hi @ACatThatPrograms, glad you like it. You're right the list endpoint doesn't return the fields. You can [see the code that removes them here](https://github.com/contentjet/contentjet-api/blob/develop/src/viewsets/EntryViewSet.ts#L177).

I did it that way intentionally as I assume the more common use-case is to just list the bare-minimum when rendering a list of entries (the title and id for example). I didn't want to send unnecessary data over-the-wire.

Perhaps it can be changed so a requester can opt-in via a url param which makes the endpoint return complete records e.g. `?complete=1`. PR welcome.

**Comment by ACatThatPrograms** [comment]
Hey thank you so much for replying like instantaneously!

I plan on following this, and I will take a look if I have time, I'm researching various solutions for a CMS system to integrate with an existing large scale platform and this almost perfectly fits the bill. I actually may dive in a little bit now, but no promises.

Thanks for putting me in the right direction and if I get it going without too much time investment I'll send a PR.

**Comment by willdady** [comment]
@ACatThatPrograms no problem! Happy to help. Full disclosure, as you can probably tell this repo is not being actively worked on. That's not to say I won't work on it again in the future but right now I'm not actively contributing. Like most things open source it needs contributors and the lack thereof seems to indicate (to me) that people aren't interested or there's other better-maintained solutions out there. Something to keep in mind in your CMS research.

**Comment by ACatThatPrograms** [comment]
Definitely noticed. Haha. You've put a lot of work into it and everything. It's really clean and concise so I hope it takes off a bit more. Definitely deserves a fighting chance among all of the available options.
